export const API_ENDPOINTS = {
  posts: '/api/posts/',
  navigation: '/api/navigation-item/',
  menuItem: '/api/menu-item/',
  department: '/api/departments/',
  tag: '/api/tags/',
  event: '/api/event/',
  slides: '/api/main-slider/',
  file: '/api/file/',
  book: '/api/book/',
  collection: '/api/book-collection/',
  uploadImage: '/api/files/upload/image',
  uploadDocument: '/api/files/upload/document',
  uploadExhibition: '/api/files/upload/exhibition',
};
